name: Backend CI - Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install backend dependencies
      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      # 4️⃣ Run backend tests
      - name: Run Jest tests
        working-directory: ./backend
        run: npm test

